POST http://localhost:3000/uploads/file
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

file
--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="test-image-1.jpg"
Content-Type: image/jpg

< ./test-image-1.jpg
--WebKitFormBoundary--