POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Mark",
  "lastName": "Doe",
  "email": "mark15@doe.com",
  "password": "Password123#"
}


POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFyazE1QGRvZS5jb20iLCJpYXQiOjE3NjI4MTc4NTQsImV4cCI6MTc2MjgyMTQ1NCwiYXVkIjoibG9jYWxob3N0IiwiaXNzIjoibG9jYWxob3N0In0.O1NL9hckZEEbHa2J_SA6A4ItUNcC3uLAaNmAtO6brVo

{
"users": [
    {
      "firstName": "John",
      "lastName": "Doe",
      "email": "john@doe.com",
      "password": "Password123#"
    },
    {
      "firstName": "Tom",
      "lastName": "Doe",
      "email": "tom@doe.com",
      "password": "Password123#"
    }
  ]
}

