GET http://localhost:3000/users/?limit=10&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFyazE1QGRvZS5jb20iLCJpYXQiOjE3NjI5MDM4MjksImV4cCI6MTc2MjkwNzQyOSwiYXVkIjoibG9jYWxob3N0IiwiaXNzIjoibG9jYWxob3N0In0.tYGVVtXZslPKtRVdC4iQhCDHuIDmBySKY3DWuAGE9Ro
