GET http://localhost:3000/users/?limit=10&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFyazE1QGRvZS5jb20iLCJpYXQiOjE3NjI4OTk5ODMsImV4cCI6MTc2MjkwMzU4MywiYXVkIjoibG9jYWxob3N0IiwiaXNzIjoibG9jYWxob3N0In0.ZCzDP5yRUOJkNA_EVW6A2DoqvDkq815DHKgRM6OrVf8
